### ISSUE TITLE
Problem trying to perform authentication

### ISSUE THREAD

**Issue by jaydeel** [bachya/simplisafe-python#453] opened 2023-03-18 02:06 UTC
I need to re-authenticate. I'm using the procedure [here](https://simplisafe-python.readthedocs.io/en/latest/usage.html#installation). Until now, this has always worked without issue.

As shown in the screenshot, the `script/setup` command produces an error Installing `sphinxcontrib-applehelp`.

Then the `script/auth` command fails to open the default browser (Chrome) so that I can log into SimpliSafe and retrieve the auth page code.

I'm using a Windows 10 machine with WSL2 installed. I'm executing the commands from bash.exe.

`python3 --version` replies "Python 3.10.6".

I get the same result when I remove the existing get clone (using `rm -rf simplisafe-python`) and repeat the procedure per the aforementioned link

![2023_03_17_18_25_41-bash - ERROR](https://user-images.githubusercontent.com/10443295/226076997-98ea2b38-84fd-4a31-9d20-f4104a836738.png)

**Comment by bachya** [comment] 2023-03-18 02:16
This issue appears to be a problem with how the Sphinx project is distributing `sphinxcontrib.applehelp`: https://github.com/sphinx-doc/sphinx/issues/11130

It isn't yet clear to me whether there is a workaround or whether we need to wait for an upstream resolution. In the meantime, it might be possible to install the packaged version of the library via `pip`:

```
pip install simplisafe-python
```

You will need to use the `auth` script outside of this parent directory so that it doesn't collide with the `pip`-installed version.

**Comment by jaydeel** [comment] 2023-03-18 20:31
After executing `pip install simplisafe-python` via bash.exe, I've confirmed that it is successfully installed in the WSL file structure (\\wsl$\Ubuntu\mnt\wslg\distro\home\jaydeel\.local\lib\python3.10\site-packages\simplipy).

And executing command `pip list` shows  'simplisafe-python 2022.12.1' in the output.

> You will need to use the `auth` script outside of this parent directory so that it doesn't collide with the `pip`-installed version.

Can you please provide a little more guidance on how to do this.

I've tried to copy the 'script/auth' script to the 'site-packages' home folder above, but it is protected by Windows.

**Comment by toddwarnock** [comment] 2023-03-25 22:46
I'm having what I think is a similar problem.  Everything works fine (except for this command "$ python3 -m virtualenv .venv" which I could only get to work by replacing the word "virtualenv" with "venv".)  However, I can't get the script to run to authorize.  See below:
![ScreenShot - Auth Failed](https://user-images.githubusercontent.com/127605883/227745896-c4036b1a-5d5f-41d9-8382-0bb4bd0118fb.png)

**Comment by jaydeel** [comment] 2023-04-01 18:09
I tried again today.

As shown in the screenshot, the `script/setup` command NO LONGER produces an error Installing sphinxcontrib-applehelp.

However, the `script/auth` command still fails to open the default browser (Chrome) so that I can log into SimpliSafe and retrieve the auth page code.

I did try changing the default browser to Edge. Same result.

![simplisafe-python auth script](https://user-images.githubusercontent.com/10443295/229307368-6fb4a2c0-aeb8-4c85-8942-b04c500b3bf3.png)

**Comment by bachya** [comment] 2023-04-01 21:08
I can confirm that the original issue—an upstream problem with Sphinx—does seem to be resolved.

I just spun up a fresh virtual environment and the `auth` script opened my browser just fine. I'm on a Mac and noticed that you're on Windows: under the hood, the `auth` script merely calls `webbrowser.open` on the appropriate SimpliSafe URL, so perhaps that call behaves differently under Windows. I recommend you create a sample script that looks like this:

```python
import webbrowser

webbrowser.open("https://google.com")
```

...run it, and see if it opens your browser correctly.

**Comment by jaydeel** [comment] 2023-04-02 05:26
I just got it to work.

1. Added the `print` lines below to the auth script.
2. Copied the URL from bash.exe.
3. Pasted the URL into my browser

```
async def main() -> None:
"""Run."""
code_verifier = get_auth0_code_verifier()
code_challenge = get_auth0_code_challenge(code_verifier)
auth_url = get_auth_url(code_challenge)
print(f"Auth URL: {auth_url}")
print()
```

**Comment by bachya** [comment] 2023-04-02 13:37
Glad you got it working. 👍🏻 Will close this issue.

**Closed by bachya** 2023-04-02 13:37 UTC
Labels: bug, python
