### ISSUE TITLE
Errors when attempting to connect to the websocket

### ISSUE THREAD

**Issue by johnlcoxjr** [bachya/simplisafe-python#226] opened 2021-04-28 00:50 UTC
I was trying to use the websocket example, but I receive an error stating that the namespace is wrong.  The websocket opens and subsequently closes.  I tried all of the other examples, and they all work.  Just this one is giving me an issue.  Any ideas?

**Comment by KTibow** [comment] 2021-04-28 01:59
What is the exact error?

**Comment by johnlcoxjr** [comment] 2021-04-28 20:56
This is what I get:

INFO:simplipy:Watchdog triggered – sleeping for 900 seconds
INFO:root:Client has connected to the websocket
ERROR:root:There was a websocket error: One or more namespaces failed to connect
INFO:root:Client has disconnected from the websocket

________________________________

**Comment by bachya** [comment] 2021-04-29 00:08
This is relatively known and likely the cause of https://github.com/home-assistant/core/issues/49513 – from that issue:

>After some investigation, not great news. It does appear that SimpliSafe is using a new websocket for events; however, the means to authenticate with that websocket rely on parameters that appear to be a combination of (a) values pulled from the device logging into the web app/mobile app/etc. and (b) one-time generated values. Without more insight into how these are created, it will not be possible for HASS to connect to the websocket.

**Comment by johnlcoxjr** [comment] 2021-04-29 00:31
Thanks for taking a look.  Have a great day!

John

On Apr 28, 2021, at 7:09 PM, Aaron Bach ***@***.***> wrote:

﻿

This is relatively known and likely the cause of home-assistant/core#49513<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fcore%2Fissues%2F49513&data=04%7C01%7C%7C04335037771f49dea67808d90aa303ed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637552517517185705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jKxT0xIgqDBDPongNnsnfuyFvUojknRXHfHSEDiZaVw%3D&reserved=0> – from that issue:

After some investigation, not great news. It does appear that SimpliSafe is using a new websocket for events; however, the means to authenticate with that websocket rely on parameters that appear to be a combination of (a) values pulled from the device logging into the web app/mobile app/etc. and (b) one-time generated values. Without more insight into how these are created, it will not be possible for HASS to connect to the websocket.

**Comment by bachya** [comment] 2021-06-06 01:24
Closing this issue per #226 – in short, the websocket that this library utilized no longer exists in the unpublished SimpliSafe cloud API.

**Closed by bachya** 2021-06-06 01:24 UTC
Labels: bug
